▽
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <MyJni.h>
#include <stdio.h>
/* Header for class TestJni */

#ifndef _Included_TestJni
#define _Included_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJni
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TestJni_print
  (JNIEnv * env, jobject object, jstring str){
	jchar *s = (jchar*)(*env)->GetStringUTFChars(env,str,NULL);
        printf("contect is %s\n", (char*)s);
        (*env)->ReleaseStringUTFChars(env, str, (const char*)s);
}

#ifdef __cplusplus
}
#endif
#endif
